### ISSUE TITLE
Random Shader Crash

### ISSUE THREAD

**Issue by woofers** [woofers/woofers3d#11]
`Exception in thread "LWJGL Application" java.lang.IllegalArgumentException: Error compiling shader: Vertex shader
Vertex shader failed to compile with the following errors:
ERROR: error(#272) Implicit version number 110 not supported by GL3 forward compatible context
ERROR: error(#273) 1 compilation errors.  No code generated

Fragment shader:
Fragment shader failed to compile with the following errors:
WARNING: 0:6: warning(#437) Extension GL_ARB_shading_language_420pack or version 4.20 is requried''.
ERROR: error(#272) Implicit version number 110 not supported by GL3 forward compatible context
ERROR: error(#273) 1 compilation errors.  No code generated

        at com.badlogic.gdx.graphics.g2d.SpriteBatch.createDefaultShader(SpriteBatch.java:163)
        at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:126)
        at com.badlogic.gdx.graphics.g2d.SpriteBatch.<init>(SpriteBatch.java:80)
        at com.jaxson.lib.gdx.graphics.views.View.<init>(View.java:37)
        at com.jaxson.lib.gdx.graphics.views.View.<init>(View.java:24)
        at com.jaxson.lib.gdx.backend.Display.<init>(Display.java:68)
        at com.jaxson.lib.gdx.backend.Game.<init>(Game.java:36)
        at com.jaxson.lib.gdx.GameInstance.create(GameInstance.java:51)
        at com.jaxson.woofers3d.Woofers3D.create(Woofers3D.java:21)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)`

Might be due to OpenGL 3.0.

**Comment by woofers** [comment]
http://badlogicgames.com/forum/viewtopic.php?t=17567&p=74319
